[app]
port = 3000
includePortInUrl = true # for eventsub, whether to send requests to :80/:443 or the port specified above.
domain = "example.com" # for eventsub, where to send the notifications
https = true # for eventsub, whether to enable HTTPs. IMPORTANT: required for Twitch (soon:tm:).
# the above would result in notifications being sent to https://example.com:3000/

# comment out what you *don't* want to disable.
disableServices = [
    "youtube", # Community Posts, videos/streams
    "twitter", # Spaces
]

[discord]
ownerId = "<Your Discord ID Here>" # If the bot encounters an error in production, you will be the first to know.
cleanupOldCommands = true # whether or not to clean up old Discord slash commands on startup
testGuildId = "<Guild ID>" # if set, will only deploy slash commands to this guild. Useful for debugging, not so useful otherwise.